Repository tigrisdata/tigris-client-ts, pull requests merged in 2023-05, with the labels that each got.

#348 feat: Pass index name along with decorated class
  src/__tests__/search/search.spec.ts
  src/__tests__/tigris.search.spec.ts
  src/search/search.ts
Labels: medium

#349 Beta release
  src/__tests__/search/search.spec.ts
  src/__tests__/tigris.search.spec.ts
  src/search/search.ts
Labels: medium

#350 feat: static type binding for query
  src/__tests__/tigris.readfields.spec.ts
  src/__tests__/tigris.utility.spec.ts
  src/collection.ts
  src/search/query.ts
  src/types.ts
  src/utility.ts
Labels: medium

#352 Beta release
  src/__tests__/tigris.readfields.spec.ts
  src/__tests__/tigris.utility.spec.ts
  src/collection.ts
  src/search/query.ts
  src/types.ts
  src/utility.ts
Labels: medium

#353 fix: turn off failing eslinter
  .eslintrc.json
Labels: small

#354 Beta release
  .eslintrc.json
Labels: small

#355 ci: restructure package.json and fix ci process
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  .github/workflows/ts-ci.yml
  package.json
Labels: small

#356 ci: audit signatures on releases
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  package.json
Labels: small

#357 Beta code update
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  .github/workflows/ts-ci.yml
  package.json
Labels: small

#358 fix: Don't use node: style imports
  .eslintrc.json
  src/__tests__/utils.ts
  src/consumables/iterable-stream.ts
  src/utils/env-loader.ts
Labels: small

#359 Beta release
  .eslintrc.json
  src/__tests__/utils.ts
  src/consumables/iterable-stream.ts
  src/utils/env-loader.ts
Labels: small

#364 fix: Handle missing decorator for model
  src/__tests__/tigris.search.spec.ts
  src/schema/decorated-schema-processor.ts
  src/search/search.ts
Labels: small

#365 fix: ping.close() callable externally
  src/tigris.ts
Labels: small

#363 feat: $push field operator for update
  src/__tests__/tigris.rpc.spec.ts
  src/__tests__/tigris.updatefields.spec.ts
  src/types.ts
  src/utility.ts
Labels: small

#369 fix: no remote call when instantiating search index
  src/__tests__/tigris.search.spec.ts
  src/search/search.ts
Labels: small

#370 Minor release
  src/__tests__/tigris.rpc.spec.ts
  src/__tests__/tigris.search.spec.ts
  src/__tests__/tigris.updatefields.spec.ts
  src/search/search.ts
  src/types.ts
  src/utility.ts
Labels: small

#371 fix: Revert "feat: static type binding for query"
  src/__tests__/tigris.readfields.spec.ts
  src/__tests__/tigris.utility.spec.ts
  src/collection.ts
  src/search/query.ts
  src/types.ts
  src/utility.ts
Labels: medium

#372 Release
  src/__tests__/tigris.readfields.spec.ts
  src/__tests__/tigris.utility.spec.ts
  src/collection.ts
  src/search/query.ts
  src/types.ts
  src/utility.ts
Labels: medium

#373 fix: Revert "feat: static type binding for query"
  src/__tests__/tigris.readfields.spec.ts
  src/__tests__/tigris.utility.spec.ts
  src/collection.ts
  src/search/query.ts
  src/types.ts
  src/utility.ts
Labels: medium

#374 Release
  src/__tests__/tigris.readfields.spec.ts
  src/__tests__/tigris.utility.spec.ts
  src/collection.ts
  src/search/query.ts
  src/types.ts
  src/utility.ts
Labels: medium

#375 fix: relax filter type checking
  src/__tests__/tigris.filters.spec.ts
  src/types.ts
Labels: small

#376 Release
  src/__tests__/tigris.filters.spec.ts
  src/types.ts
Labels: small

#380 fix: GRPC Retry on transient failure
  package-lock.json
  package.json
  src/__tests__/test-search-service.ts
  src/__tests__/test-service.ts
  src/__tests__/tigris.rpc.spec.ts
  src/__tests__/tigris.search.spec.ts
  src/tigris.ts
Labels: large

#378 chore: Improve error logging when project name in use does not exist on Tigris
  src/__tests__/tigris.rpc.spec.ts
  src/db.ts
Labels: small
